/* Auto-generated by genmsg_cpp for file /home/userws3/git/robil/C11_OperatorControl/msg/C11AC11_PUSH.msg */
#ifndef C11_OPERATORCONTROL_MESSAGE_C11AC11_PUSH_H
#define C11_OPERATORCONTROL_MESSAGE_C11AC11_PUSH_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"


namespace C11_OperatorControl
{
template <class ContainerAllocator>
struct C11AC11_PUSH_ {
  typedef C11AC11_PUSH_<ContainerAllocator> Type;

  C11AC11_PUSH_()
  : typ(0)
  {
  }

  C11AC11_PUSH_(const ContainerAllocator& _alloc)
  : typ(0)
  {
  }

  typedef int8_t _typ_type;
  int8_t typ;


  typedef boost::shared_ptr< ::C11_OperatorControl::C11AC11_PUSH_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::C11_OperatorControl::C11AC11_PUSH_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct C11AC11_PUSH
typedef  ::C11_OperatorControl::C11AC11_PUSH_<std::allocator<void> > C11AC11_PUSH;

typedef boost::shared_ptr< ::C11_OperatorControl::C11AC11_PUSH> C11AC11_PUSHPtr;
typedef boost::shared_ptr< ::C11_OperatorControl::C11AC11_PUSH const> C11AC11_PUSHConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::C11_OperatorControl::C11AC11_PUSH_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::C11_OperatorControl::C11AC11_PUSH_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace C11_OperatorControl

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::C11_OperatorControl::C11AC11_PUSH_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::C11_OperatorControl::C11AC11_PUSH_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::C11_OperatorControl::C11AC11_PUSH_<ContainerAllocator> > {
  static const char* value() 
  {
    return "466a711de37cfcd91673a69f3d7c5085";
  }

  static const char* value(const  ::C11_OperatorControl::C11AC11_PUSH_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x466a711de37cfcd9ULL;
  static const uint64_t static_value2 = 0x1673a69f3d7c5085ULL;
};

template<class ContainerAllocator>
struct DataType< ::C11_OperatorControl::C11AC11_PUSH_<ContainerAllocator> > {
  static const char* value() 
  {
    return "C11_OperatorControl/C11AC11_PUSH";
  }

  static const char* value(const  ::C11_OperatorControl::C11AC11_PUSH_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::C11_OperatorControl::C11AC11_PUSH_<ContainerAllocator> > {
  static const char* value() 
  {
    return "int8 typ\n\
";
  }

  static const char* value(const  ::C11_OperatorControl::C11AC11_PUSH_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::C11_OperatorControl::C11AC11_PUSH_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::C11_OperatorControl::C11AC11_PUSH_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.typ);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct C11AC11_PUSH_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::C11_OperatorControl::C11AC11_PUSH_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::C11_OperatorControl::C11AC11_PUSH_<ContainerAllocator> & v) 
  {
    s << indent << "typ: ";
    Printer<int8_t>::stream(s, indent + "  ", v.typ);
  }
};


} // namespace message_operations
} // namespace ros

#endif // C11_OPERATORCONTROL_MESSAGE_C11AC11_PUSH_H

