/* Auto-generated by genmsg_cpp for file /home/userws3/git/robil/C21_VisionAndLidar/msg/C21_PANORAMA.msg */
#ifndef C21_VISIONANDLIDAR_MESSAGE_C21_PANORAMA_H
#define C21_VISIONANDLIDAR_MESSAGE_C21_PANORAMA_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"


namespace C21_VisionAndLidar
{
template <class ContainerAllocator>
struct C21_PANORAMA_ {
  typedef C21_PANORAMA_<ContainerAllocator> Type;

  C21_PANORAMA_()
  : cmd(0)
  {
  }

  C21_PANORAMA_(const ContainerAllocator& _alloc)
  : cmd(0)
  {
  }

  typedef int32_t _cmd_type;
  int32_t cmd;

  enum { TAKE_PICTURE = 0 };
  enum { RETURN_PANORAMA = 1 };

  typedef boost::shared_ptr< ::C21_VisionAndLidar::C21_PANORAMA_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::C21_VisionAndLidar::C21_PANORAMA_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct C21_PANORAMA
typedef  ::C21_VisionAndLidar::C21_PANORAMA_<std::allocator<void> > C21_PANORAMA;

typedef boost::shared_ptr< ::C21_VisionAndLidar::C21_PANORAMA> C21_PANORAMAPtr;
typedef boost::shared_ptr< ::C21_VisionAndLidar::C21_PANORAMA const> C21_PANORAMAConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::C21_VisionAndLidar::C21_PANORAMA_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::C21_VisionAndLidar::C21_PANORAMA_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace C21_VisionAndLidar

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::C21_VisionAndLidar::C21_PANORAMA_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::C21_VisionAndLidar::C21_PANORAMA_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::C21_VisionAndLidar::C21_PANORAMA_<ContainerAllocator> > {
  static const char* value() 
  {
    return "10ab30b0b670abb43a0cc2b3163f5f93";
  }

  static const char* value(const  ::C21_VisionAndLidar::C21_PANORAMA_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x10ab30b0b670abb4ULL;
  static const uint64_t static_value2 = 0x3a0cc2b3163f5f93ULL;
};

template<class ContainerAllocator>
struct DataType< ::C21_VisionAndLidar::C21_PANORAMA_<ContainerAllocator> > {
  static const char* value() 
  {
    return "C21_VisionAndLidar/C21_PANORAMA";
  }

  static const char* value(const  ::C21_VisionAndLidar::C21_PANORAMA_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::C21_VisionAndLidar::C21_PANORAMA_<ContainerAllocator> > {
  static const char* value() 
  {
    return "int32 cmd\n\
int32 TAKE_PICTURE=0\n\
int32 RETURN_PANORAMA=1\n\
";
  }

  static const char* value(const  ::C21_VisionAndLidar::C21_PANORAMA_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::C21_VisionAndLidar::C21_PANORAMA_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::C21_VisionAndLidar::C21_PANORAMA_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.cmd);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct C21_PANORAMA_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::C21_VisionAndLidar::C21_PANORAMA_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::C21_VisionAndLidar::C21_PANORAMA_<ContainerAllocator> & v) 
  {
    s << indent << "cmd: ";
    Printer<int32_t>::stream(s, indent + "  ", v.cmd);
  }
};


} // namespace message_operations
} // namespace ros

#endif // C21_VISIONANDLIDAR_MESSAGE_C21_PANORAMA_H

