/* Auto-generated by genmsg_cpp for file /home/userws3/git/robil/C21_VisionAndLidar/msg/C21_PICTURE.msg */
#ifndef C21_VISIONANDLIDAR_MESSAGE_C21_PICTURE_H
#define C21_VISIONANDLIDAR_MESSAGE_C21_PICTURE_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"


namespace C21_VisionAndLidar
{
template <class ContainerAllocator>
struct C21_PICTURE_ {
  typedef C21_PICTURE_<ContainerAllocator> Type;

  C21_PICTURE_()
  : cmd(0)
  {
  }

  C21_PICTURE_(const ContainerAllocator& _alloc)
  : cmd(0)
  {
  }

  typedef int32_t _cmd_type;
  int32_t cmd;

  enum { LEFT = 0 };
  enum { RIGHT = 1 };

  typedef boost::shared_ptr< ::C21_VisionAndLidar::C21_PICTURE_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::C21_VisionAndLidar::C21_PICTURE_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct C21_PICTURE
typedef  ::C21_VisionAndLidar::C21_PICTURE_<std::allocator<void> > C21_PICTURE;

typedef boost::shared_ptr< ::C21_VisionAndLidar::C21_PICTURE> C21_PICTUREPtr;
typedef boost::shared_ptr< ::C21_VisionAndLidar::C21_PICTURE const> C21_PICTUREConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::C21_VisionAndLidar::C21_PICTURE_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::C21_VisionAndLidar::C21_PICTURE_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace C21_VisionAndLidar

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::C21_VisionAndLidar::C21_PICTURE_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::C21_VisionAndLidar::C21_PICTURE_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::C21_VisionAndLidar::C21_PICTURE_<ContainerAllocator> > {
  static const char* value() 
  {
    return "b3bb356355c682394b32c0a11debc36e";
  }

  static const char* value(const  ::C21_VisionAndLidar::C21_PICTURE_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xb3bb356355c68239ULL;
  static const uint64_t static_value2 = 0x4b32c0a11debc36eULL;
};

template<class ContainerAllocator>
struct DataType< ::C21_VisionAndLidar::C21_PICTURE_<ContainerAllocator> > {
  static const char* value() 
  {
    return "C21_VisionAndLidar/C21_PICTURE";
  }

  static const char* value(const  ::C21_VisionAndLidar::C21_PICTURE_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::C21_VisionAndLidar::C21_PICTURE_<ContainerAllocator> > {
  static const char* value() 
  {
    return "int32 cmd\n\
int32 LEFT=0\n\
int32 RIGHT=1\n\
";
  }

  static const char* value(const  ::C21_VisionAndLidar::C21_PICTURE_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::C21_VisionAndLidar::C21_PICTURE_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::C21_VisionAndLidar::C21_PICTURE_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.cmd);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct C21_PICTURE_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::C21_VisionAndLidar::C21_PICTURE_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::C21_VisionAndLidar::C21_PICTURE_<ContainerAllocator> & v) 
  {
    s << indent << "cmd: ";
    Printer<int32_t>::stream(s, indent + "  ", v.cmd);
  }
};


} // namespace message_operations
} // namespace ros

#endif // C21_VISIONANDLIDAR_MESSAGE_C21_PICTURE_H

