/* Auto-generated by genmsg_cpp for file /home/userws3/git/robil/C21_VisionAndLidar/msg/C21_RECT.msg */
#ifndef C21_VISIONANDLIDAR_MESSAGE_C21_RECT_H
#define C21_VISIONANDLIDAR_MESSAGE_C21_RECT_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"


namespace C21_VisionAndLidar
{
template <class ContainerAllocator>
struct C21_RECT_ {
  typedef C21_RECT_<ContainerAllocator> Type;

  C21_RECT_()
  : x1(0)
  , y1(0)
  , x2(0)
  , y2(0)
  {
  }

  C21_RECT_(const ContainerAllocator& _alloc)
  : x1(0)
  , y1(0)
  , x2(0)
  , y2(0)
  {
  }

  typedef int32_t _x1_type;
  int32_t x1;

  typedef int32_t _y1_type;
  int32_t y1;

  typedef int32_t _x2_type;
  int32_t x2;

  typedef int32_t _y2_type;
  int32_t y2;


  typedef boost::shared_ptr< ::C21_VisionAndLidar::C21_RECT_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::C21_VisionAndLidar::C21_RECT_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct C21_RECT
typedef  ::C21_VisionAndLidar::C21_RECT_<std::allocator<void> > C21_RECT;

typedef boost::shared_ptr< ::C21_VisionAndLidar::C21_RECT> C21_RECTPtr;
typedef boost::shared_ptr< ::C21_VisionAndLidar::C21_RECT const> C21_RECTConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::C21_VisionAndLidar::C21_RECT_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::C21_VisionAndLidar::C21_RECT_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace C21_VisionAndLidar

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::C21_VisionAndLidar::C21_RECT_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::C21_VisionAndLidar::C21_RECT_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::C21_VisionAndLidar::C21_RECT_<ContainerAllocator> > {
  static const char* value() 
  {
    return "01b404007f6687249fa0f27eea3c1daf";
  }

  static const char* value(const  ::C21_VisionAndLidar::C21_RECT_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x01b404007f668724ULL;
  static const uint64_t static_value2 = 0x9fa0f27eea3c1dafULL;
};

template<class ContainerAllocator>
struct DataType< ::C21_VisionAndLidar::C21_RECT_<ContainerAllocator> > {
  static const char* value() 
  {
    return "C21_VisionAndLidar/C21_RECT";
  }

  static const char* value(const  ::C21_VisionAndLidar::C21_RECT_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::C21_VisionAndLidar::C21_RECT_<ContainerAllocator> > {
  static const char* value() 
  {
    return "int32 x1\n\
int32 y1\n\
int32 x2\n\
int32 y2\n\
";
  }

  static const char* value(const  ::C21_VisionAndLidar::C21_RECT_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::C21_VisionAndLidar::C21_RECT_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::C21_VisionAndLidar::C21_RECT_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.x1);
    stream.next(m.y1);
    stream.next(m.x2);
    stream.next(m.y2);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct C21_RECT_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::C21_VisionAndLidar::C21_RECT_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::C21_VisionAndLidar::C21_RECT_<ContainerAllocator> & v) 
  {
    s << indent << "x1: ";
    Printer<int32_t>::stream(s, indent + "  ", v.x1);
    s << indent << "y1: ";
    Printer<int32_t>::stream(s, indent + "  ", v.y1);
    s << indent << "x2: ";
    Printer<int32_t>::stream(s, indent + "  ", v.x2);
    s << indent << "y2: ";
    Printer<int32_t>::stream(s, indent + "  ", v.y2);
  }
};


} // namespace message_operations
} // namespace ros

#endif // C21_VISIONANDLIDAR_MESSAGE_C21_RECT_H

